config/routes.rb
Cal3::Application.routes.draw do
  resources :exp_plans

  root :to => 'exp_plans#index'

end

app/models/exp_plan.rb
class ExpPlan < ActiveRecord::Base
  attr_accessible :planDay, :userName, :roomName
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exp_plans_controller.rb
# -*- coding: utf-8 -*-
class ExpPlansController < ApplicationController
  http_basic_authenticate_with :name => "pico", :password => "2012"
  # GET /exp_plans
  # GET /exp_plans.json
  def index

    t = Time.now
    strDate = t.strftime("%Y-%m-%d")
    dateAry = strDate.split("-")
    @date = Date.new(dateAry[0].to_i, dateAry[1].to_i, dateAry[2].to_i)

    @year = dateAry[0]
    @month = dateAry[1]
    @day = dateAry[2]
    @fd = t.strftime("%w")
    @ld = t.at_end_of_month.day

    #作製
    @exp_new = ExpPlan.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exp_plans }
    end
  end

  def edit
    @exp_plan = ExpPlan.find(params[:id])
  end

  def update
    @exp_plan = ExpPlan.find(params[:id])
    if @exp_plan.update_attributes(params[:post])
      redirect_to root_path, notice: '更新されました！'
    else
      render action: 'edit'
    end
  end

  # POST /exp_plans
  # POST /exp_plans.json
  def create
    @exp_plan = ExpPlan.new(params[:exp_plan])

    respond_to do |format|
      if @exp_plan.save
        redirect_to(root_path)
#        format.html { redirect_to @exp_plan, notice: 'Exp plan was successfully created.' }
 #       format.json { render json: @exp_plan, status: :created, location: @exp_plan }
      else
  #      format.html { render action: "new" }
   #     format.json { render json: @exp_plan.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /exp_plans/1
  # DELETE /exp_plans/1.json
  def destroy
    @exp_plan = ExpPlan.find(params[:id])
    @exp_plan.destroy

    respond_to do |format|
      format.html { redirect_to exp_plans_path}#exp_plans_url }
      format.json { head :no_content }
    end

    #今度ajaxにする    
    #render json: { exp: @exp_plan }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exp_plans_helper.rb
# -*- coding: utf-8 -*-
module ExpPlansHelper

  def createBlank(kaisuu)
    t = Time.now
    strDate = t.strftime("%Y-%m-%d")
    dateAry = strDate.split("-")
    date = Date.new(dateAry[0].to_i, dateAry[1].to_i, dateAry[2].to_i)

    s = "<tr>"
    for i in 0...7
      d = date + i + 7 * kaisuu
      
      s << '<td class="blank">
            <div class="ui-widget-content">
            <ol>'
            
      @array = (sarchMember(d))

      @array.each do |array|
        s << '<li class="schedule">' + array.userName + '</li>'
      end

      if @array[0] == nil

        s <<   '<li class="placeholder">予定なし</li>'
      end
      s << '</ol>
            </div>
            </td>'
    end
    s << "</tr>"
    return s
  end

  def sarchMember (date, roomName)
    
    @member = ExpPlan.where('planDay = ? and roomName = ?', date.to_s, roomName.to_s)
    return @member
    
  end

  def weekHeader
    
    t = Time.now
    date = t.strftime("%Y-%m-%d")
    dateAry = date.split("-")
    year = dateAry[0]
    month = dateAry[1]
    day = dateAry[2]

    s = '<tr class="week-header">'
    j = 0
    d = day.to_i

    #曜日
    for i in 0...7
      i = i + t.strftime("%w").to_i
      case i%7
        when 0
          s << '<th class="sun">Sun</th>'
        when 1
          s << "<th>Mon</th>"
        when 2
          s << "<th>Tue</th>"
        when 3
          s << "<th>Wed</th>"
        when 4
          s << "<th>Thu</th>"
        when 5
          s << "<th>Fri</th>"
        when 6
          s << '<th class="sat">Sat</th>'
        

      end
    end
    
    s << "</tr>"
  end
  
  def createDayLabel(kaisuu)
    t = Time.now
    date = t.strftime("%Y-%m-%d")
    dateAry = date.split("-")
    year = dateAry[0]
    month = dateAry[1]
    day = dateAry[2]

    s = '<tr class="dayLabel">'
    j = 0
    d = day.to_i + kaisuu * 7

    #日にち
    while j < 7
      j = j + 1 
      
=begin      if j == 8
        s << "</tr><tr>"
        s << createBlank(0)
      end
=end

      if d  > t.at_end_of_month.day 
        d = d - t.at_end_of_month.day
        nextMonth = month.to_i + 1
        
        if kaisuu == 0
          case d%7
          when 0 #日曜
            s << '<td class="sun lbl"><a href="#" rel="popover">' + nextMonth.to_s + "/" + d.to_s + "</a></td>"       
          when 6 #土曜
            s << '<td class="sat lbl"><a href="#" rel="popover">' + nextMonth.to_s + "/" + d.to_s + "</a></td>"
          else #平日
            s << '<td class="lbl"><a href="#" rel="popover">' + nextMonth.to_s + "/" + d.to_s + "</a></td>"       
          end
          
        else
          case d%7
          when 0 #日曜
            s << '<td class="sun lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"
          when 6 #土曜
            s << '<td class="sat lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"
          else #平日
            s << '<td class="lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"       
          end
        end 
        
      else
      
        case d%7
        when 2 #日曜
          #s << '<td class="sun lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"
          s << tdATug(d.to_s, 0)
        when 1 #土曜
          #s << '<td class="sat lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"
          s << tdATug(d.to_s, 1)
        else #平日
          #s << '<td class="lbl"><a href="#" rel="popover">' + d.to_s + "</a></td>"       
          s << tdATug(d.to_s, 2)
        end
      end
      d = d + 1
    end

#     << createBlank(1)

    s << "</tr>"
  end
  def tdATug (str, week)
    case week
      when 0
        return '<td class="sun lbl"><a href="#" class="sun" rel="popover" data-original-title="補足情報" data-content="詳しい情報"> ' + str + "</a></td>"
      when 1
        return '<td class="sat lbl"><a href="#" rel="popover">' + str + "</a></td>"
      else
        return '<td class="lbl"><a href="#" rel="popover">' + str + "</a></td>"
      end
  end




  def changeDate(date, i)
=begin    t = Time.now
    strDate = t.strftime("%Y-%m-%d")
    dateAry = strDate.split("-")
    date1 = Date.new(dateAry[0], dateAry[1], dateAry[2])
=end
    d = date + i
    return d
  end

end

app/views/exp_plans/_form.html.erb
<%= form_for(@exp_plan) do |f| %>
  <% if @exp_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exp_plan.errors.count, "error") %> prohibited this exp_plan from being saved:</h2>

      <ul>
      <% @exp_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userName %><br />
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :planDay %><br />
    <%= f.date_select :planDay %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exp_plans/edit.html.erb
<h1>Editing exp_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @exp_plan %> |
<%= link_to 'Back', exp_plans_path %>

app/views/exp_plans/index.html.erb
<h1>実験室予定表<h2>( <%= @year + "." + @month + "." + @day%>現在)</h2></h1>
 </h1>
<div class="container">
  <table class="span9 rigaku">
    <thead><th class="top ui-widget-header" colspan="7">理学</th></thead>
    <%= raw(weekHeader) %>
    

    <!-- 日付と氏名 -->
    <% for m in 0..1 -%>
      <%= raw(createDayLabel(m)) %>
      <tr>	  
	<% for i in 0...7 -%>
	  <td class="blank">
	    <% d = (changeDate(@date, i + 7*m)) %>
	    <% dd = d.strftime("%Y/%m/%d") -%>
	    <ol id="<%= dd.to_s %>" class="0">
	      <% @exp = (sarchMember(d, 0)) -%>
	      <%  @exp.each do |exp| %>
		<li id="exp_<%= exp.id %>"><strong>
		    <%= exp.userName %>
		    <%#= link_to sanitize('<i class="icon-trash"></i>'), exp, method: :delete, data:, { confirm: '削除してもよろしいでしょうか？？'},
						       :remote => true %>
		  <%= link_to sanitize('<i class="icon-trash"></i>'), exp, method: :delete
						       %></strong>
		</li>
	      <% end %>
	      <% if @exp[0] == nil %>
		<li class="placeholder">予定なし</li>
	      <% end -%>
	    </ol>
	  </td>
	<% end -%>
      </tr>
    <% end -%>

  </table>
  <table class="span9 kankyou">
    <thead><th class="top ui-widget-header" colspan="7">環境</th></thead>
    <%= raw(weekHeader) %>
      
    
    <!-- 日付と氏名 -->
    <% for m in 0..1 -%>
      <%= raw(createDayLabel(m)) %>
      <tr>	  
	<% for i in 0...7 -%>
	  <td class="blank">
	    <% d = (changeDate(@date, i + 7*m)) %>
	    <% dd = d.strftime("%Y/%m/%d") -%>
	    <ol id="<%= dd.to_s %>" class="1">
	      <% @exp = (sarchMember(d, 1)) -%>
	      <%  @exp.each do |exp| %>
		<li id="exp_<%= exp.id %>"><strong>
    		  <%= exp.userName %>

		    <%#= link_to exp.userName, edit_exp_plan_path %>
		    <%#= link_to sanitize('<i class="icon-trash"></i>'), exp, method: :delete, data: { confirm: '削除してもよろしいでしょうか？？'},
						       :remote => true %>
		  <%= link_to sanitize('<i class="icon-trash"></i>'), exp, method: :delete
						       %></strong>
		</li>
	      <% end %>
	      <% if @exp[0] == nil %>
		<li class="placeholder">予定なし</li>
	      <% end -%>
	    </ol>
	  </td>
	<% end -%>
      </tr>
    <% end -%>
    
  </table>
</div>

<%= form_for(@exp_new, :remote => true) do |f|  %>

  <div class="field">
    <%= f.hidden_field :userName ,:value => "石橋"%>
  </div>
  <div class="field">
    <%= f.hidden_field :planDay ,:value => Time.now%>
  </div>
  <div class="field">
    <%= f.hidden_field :roomName,:value => 0 %>
  </div>
<% end %>
<script type="text/javascript">
$(function(){
  $('a[data-method="delete"]').live('ajax:success', function(e, data, status, xhr)
  {
    $('#exp_'+data.exp.id).fadeOut("slow");
    
  });
  <%# $('a[rel="popover"]').popover; %>
});
</script>  

app/views/exp_plans/new.html.erb
<h1>New exp_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', exp_plans_path %>

app/views/exp_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @exp_plan.userName %>
</p>

<p>
  <b>Planday:</b>
  <%= @exp_plan.planDay %>
</p>


<%= link_to 'Edit', edit_exp_plan_path(@exp_plan) %> |
<%= link_to 'Back', exp_plans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>実験室予定表</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <!-- header -->
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
	
      
	<a href="<%= root_path %>" class="brand">MaruoLab's Schedule</a>
	<ul class="nav">
	  <li><a href="http://www.mnt.ynu.ac.jp/mlab/index.html">MaruoLab.HP</a></li>
	</ul>
<!--	<ul class="nav pull-right">
	  <li class="dropdown">
	    <a href="" class="dropdown-toggle" data-toggle="dropdown">
	      UserName
	      <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li><a href="">Setting</a> </li>
	      <li><a href="">Logout</a> </li>
	    </ul>
-->	    
	  </li>
	</ul>
      </div>
    </div>
  </div>
  <!-- Container -->
  <div class="container">
    
    <!-- Main -->
    <div class="span9">
      <%= yield %>
    </div>
    
    <!-- Sidebar -->
    <div class="span2 sidebar">
      <div id="labMem" class="span2">
      <h3 class="labMem-header" align="center">ラボメン</h3>
      <div id="member" class="">
	<ul class="member">
	  <li>石橋</li>
	  <li>杉山</li>
	  <li>椿</li>
      <li>伊原</li>
	  <li>谷口</li>
	  <li>横山</li>
	  <li>大庭</li>
      <li>駒田</li>
      <li>針金</li>
      <li>城谷</li>
	</ul>
      </div>
    </div>
    </div>
  </div>
  </div>
</div>
</body>
</html>